AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - bundle//*
    - bin/*
    - vendor//*
    - node_modules//*
    - public//*
    - db//*
    - lib//*
    - config/unicorn.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*.rb
    - config/**/*
    - script/**

Layout/DefEndAlignment:
  AutoCorrect: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/initializers/**
    - config/environments/**
    - config/schedule.rb